Algoritmo "caso.com.times"

Var
time: caracter


Inicio
escreval("Digite o seu time ")
leia(time)

escolha time
     caso "São paulo","Palmeiras","Corinthians"
          escreval("Seu time é paulista")

     caso "Flamengo","Vasco","Bota fogo"
          escreval("Seu time é Carioca")

     caso "Gremio","Cruzeiro","Inter"
          escreval("Seu time é paulista")

     outrocaso
          escreval("INVALIDO")
fimescolha

Fimalgoritmo
